### ISSUE TITLE
New Chrome warning: The keyword 'slider-vertical' specified to an 'appearance' property is not standardized.

### ISSUE THREAD

**Issue by vladimirlogachev** [mdgriffith/elm-ui#354]
**Welcome!**

Regardless of whether the app uses a vertical slider or not, the elm-ui adds the following code:

```css
input[type=range][orient=vertical]{
    writing-mode: bt-lr; /* IE */
    -webkit-appearance: slider-vertical;  /* WebKit */
}
```

This leads to the following warning in modern Chrome:

```
The keyword 'slider-vertical' specified to an 'appearance' property is not standardized. It will be removed in the future.
```

It can even be observed on https://elm-lang.org/, which also uses elm-ui these days.

Could it be that we can switch one solution for styling a vertical slider to another, using [the same old StackOverflow discussion](https://stackoverflow.com/questions/15935837/how-to-display-a-range-input-slider-vertically), which appears to describe the current approach as well?

**Expected behavior**
No warnings in the browser console

**Versions**
 - OS: macOS
 - Browser: Chrome
 - Browser Version: 115.0.5790.114 (Official Build) (arm64)
 - Elm Version: 0.19.1
 - Elm UI Version: 1.1.8
