### ISSUE TITLE
external fonts can currently only use outdated file formats

### ISSUE THREAD

**Issue by PixelPartner** [mdgriffith/elm-ui#38]
To define a *@font-face* in CSS with a modern format like `woff2`, we not only need an `url()` but also an additional  `format('woff2')` like so

```css
/* roboto-regular - latin */
@font-face {
  font-family: 'Roboto';
  font-style: normal;
  font-weight: 400;
  src: url('../fonts/roboto-v18-latin-regular.woff2') format('woff2');
}
```

**Current behavior**

```elm
external :
    { url : String
    , name : String
    }
    -> Font
```

**Expected behavior**

```elm
external :
    { url : String
    , format : Maybe String
    , name : String
    }
    -> Font
```
... and `Font` should be extended to handle this as well.

**Versions**

 - OS: Windows 8.1
 - Browsers: Chrome 64, Firefox 62
 - Elm Version: 0.19
 - Elm UI Version: 1.0.0

**Comment by PixelPartner** [comment]
Seems like I totally misinterpreted the internal mechanics.
Looking at the compiles index.html, the Font.external simply forces a CSS @import.
So, when I refer to an external CSS file with my font details, everything works fine.

```css
@font-face { 
  font-family: FirstFont; 
  src: url("FirstFont.woff2") format("woff2");
  font-weight:400;
  font-style:normal;
}
```
```elm
Font.external { url="FirstFontDefining.css", name="FirstFont" }
```
